### ISSUE TITLE
“Docs” header inconsistent with the rest of vanillaframework.io

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/vanillaframework.io#104]
1\. Go to [vanillaframework.io](https://vanillaframework.io/).
2\. Click “Docs”.

What happens:
- The logo stays the same, indicating that this is the same Web site, but it jumps to a different position.
- The header size changes.
- The header colour changes.
- All the header links disappear.

It’s unlikely to inspire confidence in the quality of a CSS framework for its own Web site to be so inconsistent.

![vanilla-site-header](https://user-images.githubusercontent.com/19801137/33601923-aab635f6-d9a5-11e7-92dd-3ceeaa5cc888.gif)

**Comment by kwm14** [comment]
@matthewpaulthomas this has now been fixed in our latest 1.6.5 release updating the header navigation on vf.io 👍 
### vanillaframework.io
![screen shot 2018-01-30 at 09 35 31](https://user-images.githubusercontent.com/17748020/35558935-2e8f74d8-05a1-11e8-9a0b-f652977dee6b.png)

### docs.vanillaframework.io
![screen shot 2018-01-30 at 09 35 48](https://user-images.githubusercontent.com/17748020/35558940-32d44f1e-05a1-11e8-9100-bfbdc5a18ac9.png)

**Comment by matthewpaulthomas** [comment]
That’s a definite improvement. Of the four items I listed:
✓ the logo position is the same
✗ the header size is _nearly_ the same, only 1px different, which I’ve reported as #116
✓ the header color is the same
✗ the header links are still all missing, so I’ve reported that as #117.
